version: '2'
services:

  db_mongo:
    image: mongo:3.4.4
    container_name: graphql-db
    ports:
      - 27000:27017
    volumes:
      - db_data:/data/db

  api:
    build: .
    container_name: graphql-api
    links:
      - db_mongo:db_mongo
    volumes:
      - ./:/usr/src/app/
      - api_node_modules:/usr/src/app/node_modules
    ports:
      - 4001:4001
      - 5001:5001
    environment:
      - NODE_ENV=development
      - DB_HOST=db_mongo
      - WEB_PORT=4000
      - DB_PORT=27017
    depends_on:
      - db_mongo
    restart:
      always

  web:
    build: ../frontend
    container_name: graphql-frontend
    volumes:
      - ../frontend/:/usr/src/app/
      - web_node_modules:/usr/share/nginx/html/node_modules
    ports:
      - 3000:3000
    environment:
      - REACT_APP_SERVER_PORT=4001
    depends_on:
      - api
    links:
      - api:api
    restart:
      always

volumes:
  api_node_modules:
    driver: local
  web_node_modules:
    driver: local
  db_data:
    driver: local
